### ISSUE TITLE
Bake UVs Bug

### ISSUE THREAD

**Issue by PavelBlend** [Pyroevil/Blender-Molecular-Script#4]
if you enable the "Bake UV at ending" option, there will be an error:
```Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\molecular\__init__.py", line 769, in modal
    bpy.ops.object.mol_set_active_uv()
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\modules\bpy\ops.py", line 189, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Ошибка: Traceback (most recent call last):
  File "C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\addons\molecular\__init__.py", line 669, in execute
    mod.use_beauty = False
AttributeError: 'TriangulateModifier' object has no attribute 'use_beauty'

location: C:\Program Project\Blender Foundation\Blender 2.79\2.79\scripts\modules\bpy\ops.py:189



location: <unknown location>:-1
```

Blender version: 2.79

**Comment by johnfax** [comment]
same here.. !

**Comment by PavelBlend** [comment]
Corrected this error:
https://github.com/Pyroevil/Blender-Molecular-Script/pull/6
